### ISSUE TITLE
[Feature Request] Configure Mod Without Having It Active First

### ISSUE THREAD

**Issue by PureMindGames** [tsunamods-codes/7th-Heaven#100]
Its always seemed like such an odd restriction to me.

**Comment by chrcoluk** [comment]
Hi, yeah I think this is a good idea, we can see if its possible.

**Comment by julianxhokaxhiu** [comment]
I was trying to work on it and I have some good news and some bad news.

Good news: we could introduce this feature and it works just fine.

Bad news: 7th asks to have a mod enabled before you allowing it to be configured, because for each part of the mod you configure, 7th checks if it conflicts with whichever active mod you have enabled as well. Allowing you to configure while not being active, would allow you to put some configurations that will lead into a crash if two mods are not compatible ( or some options are not compatible between two mods for eg. )

Because of this I'd say that is safer to allow the configuration to happen only when a mod is active. I'll close this issue.
