### ISSUE TITLE
Crash log reporter issues

### ISSUE THREAD

**Issue by chrcoluk** [tsunamods-codes/7th-Heaven#103]
Some of these have been mentioned on discord already.

Some users are getting a problem that when the game is shutdown there is a generic access violation error, this seems to be a moderately common problem in windows with some software and has no known fix.  I have observed when the game actually does crash the error code is different, so I have a suggestion of adding an exception for error code '-1073741819'

In addition the feature seems to cause issues when closing the game when more than 1 copy is running, in 2.4 7h handles this fine, on the latest build 7h will usually crash.

**Comment by julianxhokaxhiu** [comment]
Thanks for the report.

> when more than 1 copy is running

More than one copy of what? The game or 7th?

> so I have a suggestion of adding an exception for error code '-1073741819'

If we do so we will stop having any report as most likely that will be the most common exit code, so ignoring is not an option. And also it's not on 7th to be fixed, so it's ok to have the report being generated.

**Comment by chrcoluk** [comment]
Yes more than one copy of the game, sorry for not making that clear.

**Comment by julianxhokaxhiu** [comment]
For me personally doing so makes 7th crash badly saying it cannot access some process info because it's still running. I think running more than one copy of the game was never tested appropriately so, I'd assume it's broken by default.

I'd be interested in having reports only with one copy of the game running only, as intended to be.
