### ISSUE TITLE
Installer for 3.9 need Admin to run.

### ISSUE THREAD

**Issue by barkermn01** [tsunamods-codes/7th-Heaven#208]
**Describe the bug**
The installer for 3.9 installing .Net 7/8 stuff all requires admin when running the 7th heaven installer they are all prompting for admin the installer should just be running as admin so all the other installers can just run without asking the user 4 separate times for UAC permission.

** Versions **
[ ] Tested on latest stable version
[ X ] Pre-release only bug

**Comment by julianxhokaxhiu** [comment]
Hey Martin, thanks for rising this issue but I'm afraid it won't be the case. The installer is set to run as non-admin on purpose because the app itself doesn't require Admin permissions, only on specific cases ( and practically none for the upcoming 4.0 stable where native Steam support will be present ).

Dependencies are fine to ask for admin permissions as there's no way to install them without and chances are you might have them installed already, if not, we're just doing a "kind gesture" to download and install them if they are missing so it's normal admin permissions are required.

Because of this, our installer will never ask for admin permissions, unless we can do that only for dependencies before installing them. Any idea here is appreciated, but having the user asked for admin permissions when we install in non-admin paths by default will result in a confusing behavior.

**Comment by barkermn01** [comment]
The operation of an app is separate from its installation, yet this distinction often leads to complications for many users. 

For instance, in my case, the software installs on the C drive by default since it's user-run without administrative privileges. As the owner of the computer, I should have the authority to choose the installation directory. It's unreasonable for the software to occupy my boot drive when I have a 2.8 TB drive available. Consequently, I've decided to avoid software that doesn't allow me to select the installation path, including Fusion 360, which consumes hundreds of gigabytes in my user directory, filling up my boot drive. Perhaps a better solution would be to offer two types of installers: one for advanced installation that runs with administrative rights, and another for standard installation.

**Comment by julianxhokaxhiu** [comment]
Sorry, maybe I'm not following you but the 7th installer today allows you to pick the path you want, you're not forced to install it on the default path. Am I misunderstanding something? Maybe send some screenshots so I can better understand what you mean, thank you.

**Comment by barkermn01** [comment]
![image](https://github.com/tsunamods-codes/7th-Heaven/assets/37368/2159bbfe-afc5-44c0-82ff-206503c4f945)
![image](https://github.com/tsunamods-codes/7th-Heaven/assets/37368/586117d7-3927-4eef-ab10-d88cb0656b7a)

Thoes are the only screens i get before installing from the installer there is no path choice screen.

**Comment by julianxhokaxhiu** [comment]
That is because InnoSetup has a functionality to detect existing installations, and if that's the case it will skip the path selection.

Try to uninstall it and run the installer again, this should appear as the first screen
![image](https://github.com/tsunamods-codes/7th-Heaven/assets/1237070/4e40cf88-f0aa-4ee2-9a80-ca017e1ad291)

**Comment by julianxhokaxhiu** [comment]
Closing as inactive. Feel free to come back in case you find any issue. Cheers!
