### ISSUE TITLE
SFX settings audio.dat and vgmstream

### ISSUE THREAD

**Issue by chrcoluk** [tsunamods-codes/7th-Heaven#52]
As I understand it now mods that require vgmstream can automatically set it when the developer configures it in their mod, meaning there is no longer a need for a visible UI setting.

In addition 7h honours what is set in the ffnx.toml if one already exists, so I suggest two things.

1 - The sfx setting is removed from 7H_GameDriver_UI.xml, as it can only cause confusion and misconfiguration at this point.

2 - In the same update the 7h installer will replace the ffnx.toml, I did check and by default sfx is actually set to audio.dat as trueodin said.  So the issue is coming from when people had previously turned it on.

**Comment by barkermn01** [comment]
This is a change from Odin's versions we have not updated to the latest version of FFNx yet this is why this change is causing a problem and will be fixed with the next release I'm working on it now I'm just waiting for Cetum to sort out my Signing Certificate there stupid Private Key Generation system is not working as it should

**Comment by barkermn01** [comment]
Ready for release.
