### ISSUE TITLE
Unable to use generate catalog button, crashes 7h (2.3.3.10)

### ISSUE THREAD

**Issue by chrcoluk** [tsunamods-codes/7th-Heaven#75]
To test

Open 7th Heaven
Click Tools menu
Click Catalog/Mod Creation Tool
Click Generare in right side of middle part of window, It should usually generate template data, but instead 7h crashes.

https://imgur.com/ImSMf62

Line 65 in attached log.

[applog.txt](https://github.com/tsunamods-codes/7th-Heaven/files/8157720/applog.txt)

**Comment by barkermn01** [comment]
Just to note, the error on here is
```
There was an error reflecting type '_7thWrapperLib.FFNxFlag'. ---> System.NotSupportedException: Cannot serialize member _7thWrapperLib.FFNxFlag.Attributes
```

So this is caused by the FFNxConfig now supported in mods, it appears the system used Reflection and the new FFNxConfig options can't be reflected causing this error, the interface should either be removed and mean modders should know how to create XML files / copy and paste and edit them or the whole UI for that will need altering to no longer use reflection but should also probably have an interface to support FFNxConfig options added to it

**Comment by julianxhokaxhiu** [comment]
The property `FFNxFlag` is now serializable and the generate button works again as intended.
