### ISSUE TITLE
[Suggestion] Add internal resolution selector in Game Driver settings

### ISSUE THREAD

**Issue by tangtang95** [tsunamods-codes/7th-Heaven#77]
The internal resolution multiplier can only be changed right now by opening the FFNx.toml file, for users, it would be easier for them to change it inside Game Driver settings. The fixed options could be `[Auto, 1x, 2x, 3x, 4x, 5x, 6x]`. The `6x` is necessary for 4k users, but I'm not sure if this will make the game lag or not. Maybe putting some warning text that tells the user that increasing this option could require more GPU processing power.

**Comment by chrcoluk** [comment]
After discussion on discord and some testing, the suggestion from me, is to hide the 1x setting as it does cause some rendering issues, but all others can be made visible in the UI (1x can of course still be set manually).

Also since we want to get a new stable out as soon as possible, the ideal time would be to put this in canary after the next stable is released, so it gets some public testing.

**Comment by chrcoluk** [comment]
This has been implemented.
