### ISSUE TITLE
[Suggestion] Add steam achievements toggle somewhere

### ISSUE THREAD

**Issue by tangtang95** [tsunamods-codes/7th-Heaven#78]
This would help users in activating the steam achievements flag without opening FFNx.toml. I suppose for now we can put this also in Game Driver settings (maybe in Advanced tab). Also put a warning message to tell user the necessary requirements such as Steam needs to be running and online to be working

**Comment by chrcoluk** [comment]
Since we want to get a new stable out as soon as possible, the ideal time would be to put this in canary after the next stable is released, so it gets some public testing.

**Comment by julianxhokaxhiu** [comment]
Also I think this instead of being just a toggle, could be actually an entire feature that detects if you got Steam open or not, and enables/disables the flag accordingly. So it's transparent to the user, and all it needs to do is make sure Steam is opened before launching 7th ( or if they do launch 7th from Steam, this ensures Steam is open anyway when the game will be launched ).

**Comment by tangtang95** [comment]
I'm not sure if steam achievements is compatible with all mods. I heard someone having problems with new threat. So having it automatically enabled might be a problem.

**Comment by julianxhokaxhiu** [comment]
> I'm not sure if steam achievements is compatible with all mods. I heard someone having problems with new threat. So having it automatically enabled might be a problem.

Allright, let's add it to the Advanced section in the Game Driver panel then. Mind creating a PR?
